from_domain: 3
to_domain: 99

topics:
  /tb4_3/map:
    type: nav_msgs/msg/OccupancyGrid
    qos: {reliability: reliable, durability: transient_local, history: keep_last, depth: 1}

  /tb4_3/scan:
    type: sensor_msgs/msg/LaserScan
    qos: {reliability: best_effort, durability: volatile, history: keep_last, depth: 10}

  /tb4_3/tf:
    type: tf2_msgs/msg/TFMessage
    qos: {reliability: reliable, durability: volatile, history: keep_last, depth: 400}

  /tb4_3/tf_static:
    type: tf2_msgs/msg/TFMessage
    qos: {reliability: reliable, durability: transient_local, history: keep_last, depth: 1}

  /tb4_3/robot_description:
    type: std_msgs/msg/String
    qos: {reliability: reliable, durability: transient_local, history: keep_last, depth: 1}

  /tb4_3/odom:
    type: nav_msgs/msg/Odometry
    qos: {reliability: reliable, durability: volatile, history: keep_last, depth: 10}

  /clock:
    type: rosgraph_msgs/msg/Clock
    qos: {reliability: reliable, durability: volatile, history: keep_last, depth: 10}












